#ifndef DEF_CUNICODELIB
#define DEF_CUNICODELIB

#include <stdio.h>

#ifdef _WIN32
#include <Windows.h>
#endif

/*
Code system:
    Color	    Foreground Code	Background Code
    Black	    30				40
    Red		    31				41
    Green	    32				42
    Yellow	    33				43
    Blue	    34				44
    Magenta	    35				45
    Cyan	    36				46
    White	    37				47
*/

#define ESC_PREFIX "\x1b["
#define ESC_SUFFIX "m"

#define ESC_FG_BLACK ESC_PREFIX "30" ESC_SUFFIX
#define ESC_FG_RED ESC_PREFIX "31" ESC_SUFFIX
#define ESC_FG_GREEN ESC_PREFIX "32" ESC_SUFFIX
#define ESC_FG_YELLOW ESC_PREFIX "33" ESC_SUFFIX
#define ESC_FG_BLUE ESC_PREFIX "34" ESC_SUFFIX
#define ESC_FG_MAGENTA ESC_PREFIX "35" ESC_SUFFIX
#define ESC_FG_CYAN ESC_PREFIX "36" ESC_SUFFIX
#define ESC_FG_WHITE ESC_PREFIX "37" ESC_SUFFIX

#define ESC_BG_BLACK ESC_PREFIX "40" ESC_SUFFIX
#define ESC_BG_RED ESC_PREFIX "41" ESC_SUFFIX
#define ESC_BG_GREEN ESC_PREFIX "42" ESC_SUFFIX
#define ESC_BG_YELLOW ESC_PREFIX "43" ESC_SUFFIX
#define ESC_BG_BLUE ESC_PREFIX "44" ESC_SUFFIX
#define ESC_BG_MAGENTA ESC_PREFIX "45" ESC_SUFFIX
#define ESC_BG_CYAN ESC_PREFIX "46" ESC_SUFFIX
#define ESC_BG_WHITE ESC_PREFIX "47" ESC_SUFFIX

#define ESC_FG_B_BLACK ESC_PREFIX "90" ESC_SUFFIX
#define ESC_FG_B_RED ESC_PREFIX "91" ESC_SUFFIX
#define ESC_FG_B_GREEN ESC_PREFIX "92" ESC_SUFFIX
#define ESC_FG_B_YELLOW ESC_PREFIX "93" ESC_SUFFIX
#define ESC_FG_B_BLUE ESC_PREFIX "94" ESC_SUFFIX
#define ESC_FG_B_MAGENTA ESC_PREFIX "95" ESC_SUFFIX
#define ESC_FG_B_CYAN ESC_PREFIX "96" ESC_SUFFIX
#define ESC_FG_B_WHITE ESC_PREFIX "97" ESC_SUFFIX

#define ESC_BG_B_BLACK ESC_PREFIX "100" ESC_SUFFIX
#define ESC_BG_B_RED ESC_PREFIX "101" ESC_SUFFIX
#define ESC_BG_B_GREEN ESC_PREFIX "102" ESC_SUFFIX
#define ESC_BG_B_YELLOW ESC_PREFIX "103" ESC_SUFFIX
#define ESC_BG_B_BLUE ESC_PREFIX "104" ESC_SUFFIX
#define ESC_BG_B_MAGENTA ESC_PREFIX "105" ESC_SUFFIX
#define ESC_BG_B_CYAN ESC_PREFIX "106" ESC_SUFFIX
#define ESC_BG_B_WHITE ESC_PREFIX "107" ESC_SUFFIX

#define ESC_RESET_ALL ESC_PREFIX "0" ESC_SUFFIX

#define ESC_RESET_FG ESC_PREFIX "39" ESC_SUFFIX
#define ESC_RESET_BG ESC_PREFIX "49" ESC_SUFFIX

#define ESC_REVERSE_FG_BG_ON ESC_PREFIX "7" ESC_SUFFIX
#define ESC_REVERSE_FG_BG_OFF ESC_PREFIX "27" ESC_SUFFIX

#define ESC_BOLD_ON ESC_PREFIX "1" ESC_SUFFIX
#define ESC_FAINT_ON ESC_PREFIX "2" ESC_SUFFIX
#define ESC_BOLD_FAINT_OFF ESC_PREFIX "22" ESC_SUFFIX

#define ESC_DELETE_LINE ESC_PREFIX "2K"     //\x1b[K
#define ESC_CURSOR_HOME ESC_PREFIX "H"      //\x1b[H
#define ESC_CLEAR_SCREEN ESC_PREFIX "2J"    //\x1b[2J
#define ESC_CURSOR_NEXT_LINE ESC_PREFIX "E" //\x1b[E

// #define PRINTF_UNICODE(...) printf(__VA_ARGS__)
// #define PUTS_UNICODE(STRING) puts(STRING)

void initUnicodeLib() {
#ifdef _WIN32
    // Set ANSI escape codes
    HANDLE hOut = GetStdHandle(STD_OUTPUT_HANDLE);
    DWORD dwMode = 0;
    GetConsoleMode(hOut, &dwMode);
    dwMode |= ENABLE_VIRTUAL_TERMINAL_PROCESSING;
    SetConsoleMode(hOut, dwMode);
    // Set UTF8
    SetConsoleOutputCP(CP_UTF8);
#endif
}

#endif // !DEF_CUNICODELIB
