#ifndef DEF_CUNICODELIB
#define DEF_CUNICODELIB

/*
Code system:
    Color	    Foreground Code	Background Code
    Black	    30				40
    Red		    31				41
    Green	    32				42
    Yellow	    33				43
    Blue	    34				44
    Magenta	    35				45
    Cyan	    36				46
    White	    37				47

    Color       Bright Color	Foreground Code	Background Code
    Black	    90				100
    Red		    91				101
    Green	    92				102
    Yellow	    93				103
    Blue	    94				104
    Magenta	    95				105
    Cyan	    96				106
    White	    97				107

    Reset ALL  0

    Reset FG   39
    Reset BG   49

    Reverse FG/BG 7
    Reverse FG/BG Off 27

//    BOLD_ON 1
//    FAINT_ON 2
//    BOLD_FAINT_OFF 22

    DELETE_LINE 2K
    CURSOR_HOME H
    CLEAR_SCREEN 2J
    CURSOR_NEXT_LINE E
*/

// #define PRINTF_UNICODE(...) printf(__VA_ARGS__)
// #define PUTS_UNICODE(STRING) puts(STRING)

#define ESC_PREFIX "\x1b["
#define ESC_SUFFIX "m"

#define ESC_FG_BLACK ESC_PREFIX "30" ESC_SUFFIX
#define ESC_FG_RED ESC_PREFIX "31" ESC_SUFFIX
#define ESC_FG_GREEN ESC_PREFIX "32" ESC_SUFFIX
#define ESC_FG_YELLOW ESC_PREFIX "33" ESC_SUFFIX
#define ESC_FG_BLUE ESC_PREFIX "34" ESC_SUFFIX
#define ESC_FG_MAGENTA ESC_PREFIX "35" ESC_SUFFIX
#define ESC_FG_CYAN ESC_PREFIX "36" ESC_SUFFIX
#define ESC_FG_WHITE ESC_PREFIX "37" ESC_SUFFIX

#define ESC_BG_BLACK ESC_PREFIX "40" ESC_SUFFIX
#define ESC_BG_RED ESC_PREFIX "41" ESC_SUFFIX
#define ESC_BG_GREEN ESC_PREFIX "42" ESC_SUFFIX
#define ESC_BG_YELLOW ESC_PREFIX "43" ESC_SUFFIX
#define ESC_BG_BLUE ESC_PREFIX "44" ESC_SUFFIX
#define ESC_BG_MAGENTA ESC_PREFIX "45" ESC_SUFFIX
#define ESC_BG_CYAN ESC_PREFIX "46" ESC_SUFFIX
#define ESC_BG_WHITE ESC_PREFIX "47" ESC_SUFFIX

#define ESC_FG_B_BLACK ESC_PREFIX "90" ESC_SUFFIX
#define ESC_FG_B_RED ESC_PREFIX "91" ESC_SUFFIX
#define ESC_FG_B_GREEN ESC_PREFIX "92" ESC_SUFFIX
#define ESC_FG_B_YELLOW ESC_PREFIX "93" ESC_SUFFIX
#define ESC_FG_B_BLUE ESC_PREFIX "94" ESC_SUFFIX
#define ESC_FG_B_MAGENTA ESC_PREFIX "95" ESC_SUFFIX
#define ESC_FG_B_CYAN ESC_PREFIX "96" ESC_SUFFIX
#define ESC_FG_B_WHITE ESC_PREFIX "97" ESC_SUFFIX

#define ESC_BG_B_BLACK ESC_PREFIX "100" ESC_SUFFIX
#define ESC_BG_B_RED ESC_PREFIX "101" ESC_SUFFIX
#define ESC_BG_B_GREEN ESC_PREFIX "102" ESC_SUFFIX
#define ESC_BG_B_YELLOW ESC_PREFIX "103" ESC_SUFFIX
#define ESC_BG_B_BLUE ESC_PREFIX "104" ESC_SUFFIX
#define ESC_BG_B_MAGENTA ESC_PREFIX "105" ESC_SUFFIX
#define ESC_BG_B_CYAN ESC_PREFIX "106" ESC_SUFFIX
#define ESC_BG_B_WHITE ESC_PREFIX "107" ESC_SUFFIX

#define ESC_FG_RGB(R, G, B) ESC_PREFIX "38;2;" #R ";" #G ";" #B ESC_SUFFIX
#define ESC_BG_RGB(R, G, B) ESC_PREFIX "48;2;" #R ";" #G ";" #B ESC_SUFFIX

#define ESC_RESET_ALL ESC_PREFIX "0" ESC_SUFFIX

#define ESC_RESET_FG ESC_PREFIX "39" ESC_SUFFIX
#define ESC_RESET_BG ESC_PREFIX "49" ESC_SUFFIX

#define ESC_CLEAR_LINE ESC_PREFIX "2K"     //\x1b[K
#define ESC_CURSOR_HOME ESC_PREFIX "H"      //\x1b[H
#define ESC_CLEAR_SCREEN ESC_PREFIX "2J"    //\x1b[2J
#define ESC_CURSOR_NEXT_LINE ESC_PREFIX "E" //\x1b[E

#define ESC_BOLD_ON ESC_PREFIX "1" ESC_SUFFIX
#define ESC_BOLD_OFF ESC_PREFIX "22" ESC_SUFFIX

/* To Test or not working correctly on all devices */

//#define ESC_REVERSE_FG_BG_ON ESC_PREFIX "7" ESC_SUFFIX
//#define ESC_REVERSE_FG_BG_OFF ESC_PREFIX "27" ESC_SUFFIX

//#define ESC_BLINK_ON ESC_PREFIX "5" ESC_SUFFIX
//#define ESC_BLINK_OFF ESC_PREFIX "25" ESC_SUFFIX

//#define ESC_FAINT_ON ESC_PREFIX "2" ESC_SUFFIX
//#define ESC_FAINT_OFF ESC_PREFIX "22" ESC_SUFFIX

//#define ESC_UNDERLINE_ON ESC_PREFIX "4" ESC_SUFFIX
//#define ESC_UNDERLINE_OFF ESC_PREFIX "24" ESC_SUFFIX

// #define ESC_CURSOR_UP(ROWS) ESC_PREFIX #ROWS "A" ESC_SUFFIX
// #define ESC_CURSOR_DOWN(ROWS) ESC_PREFIX #ROWS "B" ESC_SUFFIX
// #define ESC_CURSOR_FORWARD(COLS) ESC_PREFIX #COLS "C" ESC_SUFFIX
// #define ESC_CURSOR_BACK(COLS) ESC_PREFIX #COLS "D" ESC_SUFFIX
// #define ESC_CURSOR_POS(ROW, COL) ESC_PREFIX #ROW ";" #COL "H" ESC_SUFFIX

int initUnicodeLib();

#endif // !DEF_CUNICODELIB
