name: Cpp Cmake Publish

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  upload-windows:
    name: Upload windows
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Copy src to root
        run: cp ./cUnicodeLib/cUnicodeLib.c .
      - name: Copy headers to root
        run: cp ./cUnicodeLib/cUnicodeLib.h .
      - name: Upload artifact release
        uses: actions/upload-artifact@v2
        with:
          name: artifact-windows
          path: |
            ./cUnicodeLib.c
            ./cUnicodeLib.h
  upload-ubuntu:
    name: Upload ubuntu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Copy src to root
        run: cp ./cUnicodeLib/cUnicodeLib.c .
      - name: Copy headers to root
        run: cp ./cUnicodeLib/cUnicodeLib.h .
      - name: Upload artifact release
        uses: actions/upload-artifact@v2
        with:
          name: artifact-ubuntu
          path: |
            ./cUnicodeLib.c
            ./cUnicodeLib.h
  release-project:
    name: Release project
    runs-on: ubuntu-latest
    needs: [ upload-windows, upload-ubuntu ]
    steps:
      - name: Download windows artifact content
        uses: actions/download-artifact@v2
        with:
          name: artifact-windows
      - name: Create GitHub release
        id: create-new-release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.run_number }}
          release_name: Release ${{ github.run_number }}
      - name: Archive windows release
        uses: thedoctor0/zip-release@master
        with:
          filename: release-windows.zip
      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-new-release.outputs.upload_url }}
          asset_path: release-windows.zip
          asset_name: cUnicodeLib-windows-v${{ github.run_number }}.zip
          asset_content_type: application/zip
      - name: Download ubuntu artifact content
        uses: actions/download-artifact@v2
        with:
          name: artifact-ubuntu
      - name: Archive ubuntu release
        uses: thedoctor0/zip-release@master
        with:
          filename: release-linux.tar.gz
      - name: Upload release asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-new-release.outputs.upload_url }}
          asset_path: release-linux.tar.gz
          asset_name: cUnicodeLib-linux-v${{ github.run_number }}.tar.gz
          asset_content_type: application/zip